- hosts: labcoding
  gather_facts: True
  become: no
  vars:
    docker_compose_version: "1.27.4"
  tasks:
  
    # ### Install SDK
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    become: yes
    apt: upgrade=dist

  - name: Install dependencies
    become: yes
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
      - zip
      - unzip
  
  - name: Download sdkman
    get_url:
      url: "https://get.sdkman.io"
      dest: /vagrant/sdkman
      mode: '+x'
  
  - name: Install sdkman
    ansible.builtin.shell: /vagrant/sdkman

  - name: CAT sdkman
    ansible.builtin.shell: cat "$HOME/.sdkman/bin/sdkman-init.sh"
  
  - name: Install sdkman
    ansible.builtin.shell:
      cmd: source "$HOME/.sdkman/bin/sdkman-init.sh"
    args:
      executable: /bin/bash


  - name: download candidates
    uri:
      url: 'https://api.sdkman.io/2/candidates/all'
      return_content: yes
    register: $HOME/.sdkman/candidates
    
  - name: Check sdkman
    become: no
    ansible.builtin.shell:
      cmd: "/vagrant/sdkman version"
    args:
      executable: /bin/bash